# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "rust-sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.35"
#rand = "0.8.5"

tinyrand = "0.5.0"